### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by SimonFenak** [SimonFenak/Koncorocny-projekt#2]
Sprav menu v pygame, z ktorého si možeš vybrať z piatich hier: 
1.  Raketka
2. Bludisko
3. Farebné štvorce
4. Pexeso
5. Pong

**Comment by Feko89** [comment]
Doplnil by som asi najprv hlavné menu, z ktorého by som sa dostal do ďalšieho menu s výberom týchto minihier.
