### ISSUE TITLE
Potrebný obrázok

### ISSUE THREAD

**Issue by bukajis** [SimonFenak/Koncorocny-projekt#7]
Pekný pracovný deň prajem a prosím kolegu Feča o návrh obrázka ŠTART. Urobil by som to sám ale chcel by som dodržať font a dizajn tlačidiel aby boli všetky rovnaké. 

Ďakujem za zhovievavosť .

Česť práci!

**Comment by Feko89** [comment]
Pozdravujem Pán Petrila, ak máte voľný čas, môžete kľudne vytvoriť nejaký dizajn pre tlačidlá. Ja momentálne nie som doma a aj tak by som tie, ktoré som už použil zmenil.

Česť Práci

**Comment by Feko89** [comment]
![start](https://user-images.githubusercontent.com/107096780/236267275-e388a007-c94b-4755-aa10-046ef4ad603b.png)
